[versions]
javaparser = '3.27.1'
micronaut-docs = "3.0.0"
micronaut = "4.10.8"
micronaut-test = "4.10.1"
groovy = "4.0.18"
spock = "2.3-groovy-4.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

javaparser = { module = 'com.github.javaparser:javaparser-core', version.ref = 'javaparser' }

groovy-test = { module = 'org.apache.groovy:groovy-test', version = '' }
